trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: '86a120ef-5973-426f-a6b3-97b372ecae4e'

  # Web app name
  webAppName: 'test-WebApp'

  # Agent pool name for Microsoft-hosted agent (use your self-hosted pool name if needed)
  poolName: 'web'

  # Environment name
  environmentName: 'test-WebApp'

  # Project root folder: directory containing manage.py or main python file
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version (update if required)
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: Build the Python app
  jobs:
  - job: BuildJob
    displayName: 'Build and package'
    pool:
      name: $(poolName)  # Use 'ubuntu-latest' for hosted, or your own self-hosted pool name
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Set Python version $(pythonVersion)'

    - script: |
        python -m venv antenv
        call antenv\Scripts\activate.bat
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: 'Install dependencies'
      shell: cmd
      
    - script: |
        pip install pytest pytest-azurepipelines
        pytest
      displayName: 'Run tests'

    - task: ArchiveFiles@2
      displayName: 'Archive build files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Publish build artifact'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy to Azure Web App'
    pool:
      name: $(poolName)  # Use same agent pool for deployment or specify different pool
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Set Python version for deployment'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App: $(webAppName)'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
